using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using OpenSteamTool.Manager.Models;

namespace OpenSteamTool.Manager.Services;

public sealed class TomlConfigService
{
    private static readonly Regex StringValue = new("=\\s*\"(?<v>[^\"]*)\"", RegexOptions.Compiled);
    private static readonly Regex IntValue = new("=\\s*(?<v>\\d+)", RegexOptions.Compiled);

    public TomlSettings Load(string steamPath)
    {
        var settings = new TomlSettings();
        var path = GetConfigPath(steamPath);
        if (!File.Exists(path))
        {
            return settings;
        }

        var section = string.Empty;
        foreach (var raw in File.ReadAllLines(path))
        {
            var line = raw.Trim();
            if (line.StartsWith('[') && line.EndsWith(']'))
            {
                section = line.Trim('[', ']');
                continue;
            }

            if (line.StartsWith('#') || !line.Contains('='))
            {
                continue;
            }

            if (section == "log" && line.StartsWith("level"))
            {
                settings.LogLevel = ReadString(line, settings.LogLevel);
            }
            else if (section == "manifest")
            {
                if (line.StartsWith("url"))
                {
                    settings.ManifestUrl = ReadString(line, settings.ManifestUrl);
                }
                else if (line.StartsWith("timeout_resolve_ms"))
                {
                    settings.TimeoutResolveMs = ReadInt(line, settings.TimeoutResolveMs);
                }
                else if (line.StartsWith("timeout_connect_ms"))
                {
                    settings.TimeoutConnectMs = ReadInt(line, settings.TimeoutConnectMs);
                }
                else if (line.StartsWith("timeout_send_ms"))
                {
                    settings.TimeoutSendMs = ReadInt(line, settings.TimeoutSendMs);
                }
                else if (line.StartsWith("timeout_recv_ms"))
                {
                    settings.TimeoutRecvMs = ReadInt(line, settings.TimeoutRecvMs);
                }
            }
            else if (section == "lua" && line.StartsWith("paths"))
            {
                foreach (Match match in Regex.Matches(line, "\"(?<v>[^\"]*)\""))
                {
                    settings.LuaPaths.Add(match.Groups["v"].Value);
                }
            }
        }

        return settings;
    }

    public void Save(string steamPath, TomlSettings settings)
    {
        Validate(settings);
        Directory.CreateDirectory(steamPath);
        BackupOriginalOnce(steamPath);

        var sb = new StringBuilder();
        sb.AppendLine("# opensteamtool.toml - generated by OpenSteamTool Manager");
        sb.AppendLine("# Place at: <Steam>/opensteamtool.toml");
        sb.AppendLine();
        sb.AppendLine("[log]");
        sb.AppendLine($"level = \"{settings.LogLevel.Trim().ToLowerInvariant()}\"");
        sb.AppendLine();
        sb.AppendLine("[manifest]");
        sb.AppendLine($"url = \"{settings.ManifestUrl.Trim().ToLowerInvariant()}\"");
        sb.AppendLine($"timeout_resolve_ms = {settings.TimeoutResolveMs}");
        sb.AppendLine($"timeout_connect_ms = {settings.TimeoutConnectMs}");
        sb.AppendLine($"timeout_send_ms    = {settings.TimeoutSendMs}");
        sb.AppendLine($"timeout_recv_ms    = {settings.TimeoutRecvMs}");
        sb.AppendLine();
        sb.AppendLine("[lua]");
        sb.Append("paths = [");
        sb.Append(string.Join(", ", settings.LuaPaths.Select(x => $"\"{EscapeTomlString(x)}\"")));
        sb.AppendLine("]");

        File.WriteAllText(GetConfigPath(steamPath), sb.ToString(), new UTF8Encoding(false));
    }

    public void EnsureLuaDirectory(string steamPath)
        => Directory.CreateDirectory(Path.Combine(steamPath, "config", "lua"));

    private static string GetConfigPath(string steamPath)
        => Path.Combine(steamPath, "opensteamtool.toml");

    private static string ReadString(string line, string fallback)
    {
        var match = StringValue.Match(line);
        return match.Success ? match.Groups["v"].Value : fallback;
    }

    private static int ReadInt(string line, int fallback)
    {
        var match = IntValue.Match(line);
        return match.Success && int.TryParse(match.Groups["v"].Value, out var value) ? value : fallback;
    }

    private static void Validate(TomlSettings settings)
    {
        var logLevel = settings.LogLevel.Trim().ToLowerInvariant();
        if (!new[] { "trace", "debug", "info", "warn", "error" }.Contains(logLevel))
        {
            throw new InvalidOperationException("日志等级必须是 trace/debug/info/warn/error。");
        }

        var manifestUrl = settings.ManifestUrl.Trim().ToLowerInvariant();
        if (!new[] { "steamrun", "wudrm" }.Contains(manifestUrl))
        {
            throw new InvalidOperationException("Manifest Provider 必须是 steamrun 或 wudrm。");
        }

        if (settings.TimeoutResolveMs <= 0 || settings.TimeoutConnectMs <= 0
            || settings.TimeoutSendMs <= 0 || settings.TimeoutRecvMs <= 0)
        {
            throw new InvalidOperationException("HTTP 超时时间必须大于 0。");
        }
    }

    private static void BackupOriginalOnce(string steamPath)
    {
        var source = GetConfigPath(steamPath);
        if (!File.Exists(source))
        {
            return;
        }

        var backupDir = Path.Combine(steamPath, "opensteamtool-manager", "backup");
        Directory.CreateDirectory(backupDir);
        var backup = Path.Combine(backupDir, "opensteamtool.toml.original");
        if (!File.Exists(backup))
        {
            File.Copy(source, backup);
        }
    }

    private static string EscapeTomlString(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
